version: '3.9'

services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    env_file: .env
    depends_on:
    - db

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    env_file: .env